version: '2'

services:
  django_drf:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["/app/scripts/start_server.sh"]
    environment:
      - DJANGO_SETTINGS_MODULE=django_drf.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
